#!/bin/zsh

debug() {
    [[ -f target/debug/decor8 ]] && target/debug/decor8 $@ || echo "Build debug configuration!"
}

release() {
    [[ -f target/release/decor8 ]] && target/release/decor8 $@ || echo "Build release configuration!"
}

main () {
    zparseopts -D -A _clargs -config:
    local _config=$_clargs[--config]
    [[ $_config == "debug" ]] && debug $@
    [[ $_config == "release" ]] && release $@
}

main $*
