CODE:
    graph LR
    subgraph shell
        z(ZSH)
        b(Bash)
        f(Fish)
    end
    subgraph tmux
        t(Session)
    end
    subgraph Neovim
        v(Editor)
    end
    subgraph dd[Decorator Daemon]
    subgraph fe[Front End]
        sl[Shell Listener]
        tl[tmux Listener]
        vl[Neovim Listener]
    end
    subgraph be[Back End]
        c[Config]
        sd[Shell Decorator]
        td[tmux Decorator]
        vd[Neovim Decorator]
    end
    end
    z --- sl
    b --- sl
    f --- sl
    t --- tl
    v --- vl
    sl --- sd
    tl --- td
    vl --- vd
    sd --- c
    td --- c
    vd --- c

CONFIG:
    {
  "theme": "neutral"
    }