graph LR
		DA>DA]
    DS[DSup]
    CS[CfgSup]
    SS[ShellSup]

    DA --> DS
    DS --> CS
    DS --> SS

    CfgS[CfgSvc]

    CS --> CfgS

    SheL(SheLSvc)
    SheD[ShelDSup]
    SheZ(ZSHDSvc)
    SheB(BashDSvc)
    SheF(FishDSvc)

    SS-->SheL
    SS-->SheD
    SheD-->SheZ
    SheD-->SheB
    SheD-->SheF
    SheL-.->SheZ
    SheL-.->SheB
    SheL-.->SheF
    SheZ-.->CfgS
    SheB-.->CfgS
    SheF-.->CfgS
    subgraph Client
      Shell
    end
    Shell-.->SheL
