graph LR
  /[decor8r]
  A[about]
  L[listener]
    LU[unix]
    LI[tcpip]
  R[runtime]
    RL[logger]
  D[decoration]
    DG[glyph]
      DGR[rhs]
  S[shell]
    SV[vi]
    SU[user]
    SD[path]
    SP[venv]
    SG[vcs]
      SGG[glyph]
    SJ[job]
    SS[status]
  T[tmux]
  V[vim]
  G[theme]

  / --> A
  / --> L
    L --> LU
    L --> LI
  / --> R
    R --> RL
  / --> D
    D --> DG
      DG --> DGR
    D --> S
      S --> SV
      S --> SU
      S --> SP
      S --> SD
      S --> SG
        SG --> SGG
      S --> SJ
      S --> SS
    D --> T
    D --> V
  / --> G