[glyph]
    bar = "│"
    locked = ""
    [glyph.ltr]
        terminator = ""
        separator = ""
    [glyph.rtl]
        terminator = ""
        separator = ""
    [glyph.terminal]
        ellipsis = "┅"
    [glyph.git]
        branch = ""
        stash = "§"
        conflict = "‼"
        added = "+"
        removed = "-"
        modifed = "~"
        ahead = "↑"
        behind = "↓"
        behead = "↕"
        synced = "≡"
        eol = ""
    [glyph.virtual]
        environment = "E"


[neovim]


# [terminal]
# [terminal.glyph]


[tmux]




[default.listener]
[default.listener.unix]
socket = "/tmp/decor8r.sock"
[default.listener.tcpip]
port = 65521