[glyph]
[glyph.ltr]
hard = ""
soft = ""
[glyph.rtl]
hard = ""
soft = ""


[neovim]


# [terminal]
# [terminal.glyph]
# short = "┅"
# [terminal.glyph.git]
# bar= "│"
# branch = ""
# stash = "§"
# conflict = "‼"
# add = "+"
# remove = "-"
# modify = "~"
# synced = "≡"
# ahead = "↑"
# behind = "↓"
# behead = "↕"


[tmux]




[default.listener]
[default.listener.unix]
socket = "/tmp/decor8r.sock"
[default.listener.tcpip]
port = 65521